import os

def write_file(path: str, content: str):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(content.strip() + "\n")

files = {
    "apps/web/src/app/page.tsx": """
import { ExperimentPanel } from '../components/ExperimentPanel';
import { BdhCqModule } from '../components/BdhCqModule';

export default function Home() {
  return (
    <main className="min-h-screen p-8 max-w-6xl mx-auto font-sans bg-gray-50 text-gray-900">
      <header className="mb-12 text-center pt-12">
        <h1 className="text-6xl font-extrabold tracking-tight mb-4 text-black uppercase">
          Coverage Cliff
        </h1>
        <h2 className="text-2xl text-gray-700 max-w-3xl mx-auto font-medium mb-6">
          How far can a model generalize beyond what its demonstrations actually cover?
        </h2>
        <p className="text-lg text-gray-600 max-w-2xl mx-auto mb-10">
          Give a model examples of a rule. We increase the task complexity beyond those examples and measure when, if ever, its accuracy breaks.
        </p>
      </header>

      <section className="mb-16 max-w-4xl mx-auto text-center bg-white p-8 rounded-xl border-l-4 border-black shadow-sm">
        <h3 className="text-sm font-bold uppercase tracking-widest text-gray-500 mb-4">Falsifiable Claim</h3>
        <p className="text-2xl italic font-serif text-gray-900">
          "A model can appear to generalize successfully within the complexity of its demonstrations, yet fail sharply when the same underlying rule is pushed beyond that demonstrated coverage."
        </p>
        <div className="mt-6 bg-yellow-50 text-yellow-900 p-4 rounded text-sm text-left border border-yellow-200">
          <strong>IMPORTANT:</strong> This is a task- and model-specific hypothesis, not a universal law of AI.
        </div>
      </section>

      <section className="max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8 text-sm text-gray-700 mb-16 bg-white p-8 rounded-xl border shadow-sm">
        <div>
          <h3 className="font-bold text-gray-900 mb-4 uppercase text-xs tracking-widest border-b pb-2">Terminology</h3>
          <p className="mb-4">
            <strong className="text-black">Demonstration Coverage (Cmax):</strong><br/>
            Maximum task complexity represented in the demonstrations.
          </p>
          <p>
            <strong className="text-black">Extrapolation Distance (Dext):</strong><br/>
            Dext = Ctest - Cmax<br/>
            How far the test task lies beyond the demonstrated coverage.
          </p>
        </div>
        <div>
          <h3 className="font-bold text-gray-900 mb-4 uppercase text-xs tracking-widest border-b pb-2">What counts as evidence?</h3>
          <ul className="space-y-3">
            <li><span className="inline-block bg-green-100 text-green-800 text-[10px] font-bold px-2 py-0.5 rounded uppercase mr-2 border border-green-200">OUR LIVE EXPERIMENT</span>Results generated by this project's backend.</li>
            <li><span className="inline-block bg-blue-100 text-blue-800 text-[10px] font-bold px-2 py-0.5 rounded uppercase mr-2 border border-blue-200">PUBLISHED</span>Claims directly supported by cited research.</li>
            <li><span className="inline-block bg-gray-100 text-gray-800 text-[10px] font-bold px-2 py-0.5 rounded uppercase mr-2 border border-gray-200">ILLUSTRATIVE</span>Visual explanation only.</li>
          </ul>
        </div>
      </section>

      <ExperimentPanel />

      <BdhCqModule />

      <footer className="mt-24 text-center text-sm text-gray-400 py-12 border-t">
        Coverage Cliff - Pathway / DataForge 2026 Pathway Track
      </footer>
    </main>
  );
}
""",
    "apps/web/src/components/ExperimentPanel.tsx": """
'use client';
import { useState } from 'react';
import { runExperiment } from '../lib/api';
import { ExperimentResult, ExperimentConfig } from '../lib/types';
import { ResultView } from './ResultView';

export function ExperimentPanel() {
  const [config, setConfig] = useState<ExperimentConfig>({
    master_seed: 2026,
    demonstration_count: 3,
    demonstration_complexity: 2,
    extrapolation_levels: [0, 1, 2, 3, 4],
    tasks_per_level: 5,
    evaluator_type: "deterministic",
  });
  
  const [result, setResult] = useState<ExperimentResult | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [loadingText, setLoadingText] = useState("");

  const handleRun = async () => {
    setLoading(true);
    setError(null);
    setResult(null);
    
    // Fake loading steps to visually indicate backend work pipeline
    setLoadingText("GENERATING CONTROLLED TASKS...");
    
    try {
      setTimeout(() => setLoadingText("VALIDATING GROUND TRUTH..."), 400);
      setTimeout(() => setLoadingText("EVALUATING PREDICTIONS..."), 800);
      setTimeout(() => setLoadingText("COMPUTING ACCURACY..."), 1200);
      
      const res = await runExperiment(config);
      setResult(res);
    } catch (err: any) {
      setError(err.message || 'Experiment service unavailable. Please start the backend and try again.');
    } finally {
      setTimeout(() => setLoading(false), 1300);
    }
  };

  return (
    <div className="w-full max-w-4xl mx-auto my-8">
      <div className="bg-white p-8 border rounded-xl shadow-lg relative overflow-hidden">
        
        {loading && (
          <div className="absolute inset-0 bg-white/90 backdrop-blur-sm z-10 flex flex-col items-center justify-center">
            <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-black mb-4"></div>
            <div className="font-mono text-sm font-bold tracking-widest">{loadingText}</div>
          </div>
        )}

        <div className="text-center mb-8">
          <h2 className="text-3xl font-extrabold">The Laboratory</h2>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6 mb-8 bg-gray-50 p-6 rounded-lg border">
          <div>
            <label className="block text-sm font-bold mb-1 text-gray-900">How much has the model seen?</label>
            <div className="text-xs text-gray-500 mb-2">Demonstration Coverage</div>
            <input 
              type="number" 
              className="w-full border rounded p-2" 
              value={config.demonstration_complexity} 
              onChange={e => setConfig({...config, demonstration_complexity: parseInt(e.target.value)})} 
              min={1} max={5}
            />
          </div>
          <div>
            <label className="block text-sm font-bold mb-1 text-gray-900">How far should we push beyond it?</label>
            <div className="text-xs text-gray-500 mb-2">Extrapolation Range (Max)</div>
            <input 
              type="number" 
              className="w-full border rounded p-2" 
              value={Math.max(...config.extrapolation_levels)} 
              onChange={e => {
                const max = parseInt(e.target.value);
                const levels = Array.from({length: max + 1}, (_, i) => i);
                setConfig({...config, extrapolation_levels: levels});
              }} 
              min={1} max={8}
            />
          </div>
          <div>
            <label className="block text-sm font-bold mb-1 text-gray-900">Try a different world</label>
            <div className="text-xs text-gray-500 mb-2">Random Seed</div>
            <input 
              type="number" 
              className="w-full border rounded p-2" 
              value={config.master_seed} 
              onChange={e => setConfig({...config, master_seed: parseInt(e.target.value)})} 
            />
          </div>
        </div>
        
        <div className="flex flex-col md:flex-row gap-4">
          <button 
            onClick={handleRun}
            disabled={loading}
            className="flex-1 bg-black text-white rounded-lg py-4 font-bold text-lg hover:bg-gray-800 disabled:opacity-50 transition-all shadow-md"
          >
            RUN THE EXPERIMENT
          </button>
          
          {result && (
            <button 
              onClick={() => {
                setConfig({...config, master_seed: config.master_seed + 1});
                setResult(null);
                // Trigger click visually later
              }}
              className="md:w-1/3 bg-white text-black border-2 border-black rounded-lg py-4 font-bold text-lg hover:bg-gray-50 transition-all"
            >
              CHALLENGE THE CLAIM
            </button>
          )}
        </div>
        
        {result && (
          <div className="mt-4 text-center text-xs text-gray-500 italic">
            Does the cliff move if we change the experiment? Click 'Challenge the Claim'.
          </div>
        )}
        
        {error && (
          <div className="mt-6 p-4 bg-red-50 text-red-700 rounded border border-red-200 text-sm font-medium">
            {error}
          </div>
        )}
      </div>

      {result && <ResultView result={result} seed={config.master_seed} />}
    </div>
  );
}
""",
    "apps/web/src/components/ResultView.tsx": """
'use client';
import { useState } from 'react';
import { ExperimentResult, PredictionResult } from '../lib/types';
import { AccuracyChart } from './AccuracyChart';

export function ResultView({ result, seed }: { result: ExperimentResult, seed: number }) {
  const [activeTaskIndex, setActiveTaskIndex] = useState(0);
  const [showTruth, setShowTruth] = useState(false);

  const task = result.raw_results[activeTaskIndex];
  const maxIndex = result.raw_results.length - 1;

  const handleNext = () => {
    if (activeTaskIndex < maxIndex) {
      setActiveTaskIndex(i => i + 1);
      setShowTruth(false);
    }
  };

  const handlePrev = () => {
    if (activeTaskIndex > 0) {
      setActiveTaskIndex(i => i - 1);
      setShowTruth(false);
    }
  };

  const isSharpCliff = result.cliff_detected && result.cliff_type === 'SHARP_CLIFF';
  const cliffTitle = result.cliff_detected ? 'COVERAGE CLIFF DETECTED' : (result.cliff_type === 'STABLE' ? 'NO COVERAGE CLIFF DETECTED' : result.cliff_type.replace('_', ' '));

  return (
    <div className="mt-12">
      <div className="text-center mb-6">
        <span className="inline-block bg-green-100 text-green-800 text-[10px] font-bold px-2 py-0.5 rounded uppercase border border-green-200 mb-2">OUR LIVE EXPERIMENT</span>
        <div className="text-sm text-gray-500 font-mono">Experiment Seed: {seed} | Reproducible from configuration</div>
      </div>
      
      <div className={`p-8 rounded-xl border-2 mb-8 ${result.cliff_detected ? 'bg-red-50 border-red-200' : 'bg-slate-50 border-slate-200'}`}>
        <h3 className={`font-black text-2xl mb-2 ${result.cliff_detected ? 'text-red-700' : 'text-slate-800'}`}>
          {cliffTitle}
        </h3>
        {result.estimated_cliff_location !== null && (
          <p className="font-mono text-sm mb-4">Estimated boundary: Extrapolation distance {result.estimated_cliff_location}</p>
        )}
        
        <div className="mt-4 pt-4 border-t border-black/10">
          <h4 className="font-bold text-sm uppercase tracking-widest mb-2">What this experiment shows</h4>
          <p className="text-sm text-gray-700">
            {isSharpCliff ? 
              `Under this experiment's conditions, the evaluator remained correct through the tested in-coverage and near-boundary levels, then failed sharply at extrapolation distance ${result.estimated_cliff_location}.` :
              `Under this experiment's conditions, the evaluator exhibited ${result.cliff_type.toLowerCase().replace('_', ' ')}.`
            }
          </p>
        </div>
      </div>
      
      <AccuracyChart levelMetrics={result.level_metrics} cliffLocation={result.estimated_cliff_location} />

      <div className="mt-12 border rounded-xl overflow-hidden bg-white shadow-sm">
        <div className="bg-gray-900 text-white p-6">
          <h4 className="font-bold text-lg mb-2">Task Explorer</h4>
          <div className="text-sm text-gray-300">
            Task {activeTaskIndex + 1} of {result.raw_results.length} | Extrapolation Distance: +{task.extrapolation_distance}
          </div>
        </div>
        
        <div className="p-8">
          <div className="mb-8 p-6 bg-slate-50 border rounded-lg font-mono text-sm whitespace-pre-wrap leading-relaxed">
            {task.input_representation}
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-8 mb-8">
            <div className="p-6 border-2 border-gray-200 rounded-xl bg-white relative">
              <div className="absolute -top-3 left-4 bg-white px-2 text-xs font-bold uppercase tracking-widest text-gray-500">Evaluator Prediction</div>
              <div className="text-2xl font-mono font-bold text-center py-6">{task.prediction}</div>
            </div>
            
            <div className={`p-6 border-2 rounded-xl bg-white relative transition-colors duration-500 ${showTruth ? (task.correct ? 'border-green-400 bg-green-50' : 'border-red-400 bg-red-50') : 'border-gray-200'}`}>
              <div className="absolute -top-3 left-4 bg-white px-2 text-xs font-bold uppercase tracking-widest text-gray-500 flex items-center gap-2">
                Ground Truth
              </div>
              
              {showTruth ? (
                <div className="text-center">
                  <div className="text-2xl font-mono font-bold py-6">{task.ground_truth}</div>
                  <div className={`mt-2 font-black text-lg ${task.correct ? 'text-green-600' : 'text-red-600'}`}>
                    {task.correct ? '✓ CORRECT' : '✕ INCORRECT'}
                  </div>
                </div>
              ) : (
                <div className="flex flex-col items-center justify-center py-4 h-full">
                  <p className="text-xs text-gray-400 mb-3 text-center px-4">Ground truth is generated independently from the evaluator via a Z3 exact solver.</p>
                  <button 
                    onClick={() => setShowTruth(true)} 
                    className="bg-black text-white px-6 py-2 rounded-full font-bold hover:bg-gray-800 transition-colors"
                  >
                    Reveal Ground Truth
                  </button>
                </div>
              )}
            </div>
          </div>
          
          <div className="flex justify-between items-center border-t pt-6">
            <button onClick={handlePrev} disabled={activeTaskIndex === 0} className="px-6 py-2 border-2 rounded-lg font-bold disabled:opacity-30 hover:bg-gray-50">Previous</button>
            <button onClick={handleNext} disabled={activeTaskIndex === maxIndex} className="px-6 py-2 bg-black text-white rounded-lg font-bold disabled:opacity-30 hover:bg-gray-800">Next Task</button>
          </div>
        </div>
      </div>
      
      <div className="mt-8 bg-blue-50 border border-blue-200 p-6 rounded-xl flex items-start gap-4">
        <div className="text-blue-500 mt-1">
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="2" strokeLinecap="round" strokeLinejoin="round"><circle cx="12" cy="12" r="10"></circle><line x1="12" y1="16" x2="12" y2="12"></line><line x1="12" y1="8" x2="12.01" y2="8"></line></svg>
        </div>
        <div>
          <h4 className="font-bold text-blue-900 mb-1">Methodology: Ground Truth is Trustworthy</h4>
          <p className="text-sm text-blue-800">
            Ground truth is generated independently from the evaluator via an exact mathematical solver. The evaluator does not receive the hidden rule, ground truth, or generator internals. Zero data leakage is mathematically guaranteed.
          </p>
        </div>
      </div>
    </div>
  );
}
""",
    "apps/web/src/components/AccuracyChart.tsx": """
'use client';
import { LevelMetric } from '../lib/types';

export function AccuracyChart({ levelMetrics, cliffLocation }: { levelMetrics: Record<string, LevelMetric>, cliffLocation: number | null }) {
  const data = Object.values(levelMetrics).sort((a, b) => a.extrapolation_distance - b.extrapolation_distance);
  
  return (
    <div className="p-8 border rounded-xl bg-white shadow-sm mt-8">
      <h3 className="font-bold text-xl mb-2">Accuracy vs Extrapolation Distance</h3>
      <p className="text-sm text-gray-500 mb-8">This is actual experiment data returned by the backend.</p>
      
      <div className="relative flex items-end h-72 gap-4 border-b-2 border-l-2 border-gray-300 pb-2 pl-2">
        {/* Y Axis labels */}
        <div className="absolute -left-12 bottom-0 text-xs font-mono text-gray-400">0%</div>
        <div className="absolute -left-12 top-0 text-xs font-mono text-gray-400">100%</div>
        
        {data.map((point) => {
          const isAtOrPastCliff = cliffLocation !== null && point.extrapolation_distance >= cliffLocation;
          
          return (
            <div key={point.extrapolation_distance} className="relative flex-1 flex flex-col justify-end items-center group h-full">
              <div 
                className={`w-full max-w-[60px] rounded-t transition-all duration-700 ease-out flex items-center justify-center
                  ${isAtOrPastCliff ? 'bg-red-500' : 'bg-black'}
                  hover:opacity-80
                `}
                style={{ height: `${Math.max(point.accuracy * 100, 2)}%` }} /* Min height for visibility if 0 */
              >
                {point.accuracy > 0.1 && (
                  <span className="text-white text-xs font-bold">{Math.round(point.accuracy * 100)}%</span>
                )}
              </div>
              
              <div className="absolute -bottom-8 text-sm font-mono font-bold text-gray-600">
                +{point.extrapolation_distance}
              </div>
              
              {point.accuracy <= 0.1 && (
                <div className="absolute bottom-2 text-red-100 text-xs font-bold">{Math.round(point.accuracy * 100)}%</div>
              )}
            </div>
          );
        })}
      </div>
      
      <div className="mt-12 text-center">
        <span className="inline-block px-4 py-2 bg-gray-100 text-gray-700 font-bold text-xs uppercase tracking-widest rounded">
          Extrapolation Distance (Dext)
        </span>
      </div>
    </div>
  );
}
"""
}

for path, content in files.items():
    write_file(path, content)

print("Phase 5 Frontend Polish Applied Successfully.")
