import { ExperimentPanel } from '../components/ExperimentPanel';
import { BdhCqModule } from '../components/BdhCqModule';

export default function Home() {
  return (
    <main className="min-h-screen p-8 max-w-6xl mx-auto font-sans text-slate-100">
      
      {/* Abstract background blobs for visual flair */}
      <div className="fixed inset-0 overflow-hidden pointer-events-none -z-10">
        <div className="absolute top-[-10%] left-[-10%] w-[40%] h-[40%] rounded-full bg-purple-900/20 blur-[120px]"></div>
        <div className="absolute bottom-[-10%] right-[-10%] w-[50%] h-[50%] rounded-full bg-cyan-900/10 blur-[120px]"></div>
      </div>

      <header className="mb-12 text-center pt-12 relative">
        <h1 className="text-6xl md:text-7xl font-extrabold tracking-tight mb-4 uppercase gradient-text text-glow pb-2">
          Coverage Cliff
        </h1>
        <h2 className="text-2xl text-slate-300 max-w-3xl mx-auto font-medium mb-6 leading-relaxed">
          How far can a model generalize beyond what its demonstrations actually cover?
        </h2>
        <p className="text-lg text-slate-400 max-w-2xl mx-auto mb-10">
          Give a model examples of a rule. We increase the task complexity beyond those examples and measure when, if ever, its accuracy breaks.
        </p>
      </header>

      <section className="mb-16 max-w-4xl mx-auto text-center glass-card p-8 border-l-4 border-l-purple-500">
        <h3 className="text-sm font-bold uppercase tracking-widest text-slate-400 mb-4">Falsifiable Claim</h3>
        <p className="text-2xl italic font-serif text-slate-100 leading-relaxed text-glow-cyan">
          &ldquo;A model can appear to generalize successfully within the complexity of its demonstrations, yet fail sharply when the same underlying rule is pushed beyond that demonstrated coverage.&rdquo;
        </p>
        <div className="mt-6 bg-yellow-900/30 text-yellow-200 p-4 rounded text-sm text-left border border-yellow-700/50">
          <strong className="text-yellow-400">IMPORTANT:</strong> This is a task- and model-specific hypothesis, not a universal law of AI.
        </div>
      </section>

      <section className="max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8 text-sm text-slate-300 mb-16 glass-card p-8">
        <div>
          <h3 className="font-bold text-slate-100 mb-4 uppercase text-xs tracking-widest border-b border-slate-700 pb-2">Terminology</h3>
          <p className="mb-4">
            <strong className="text-purple-300">Demonstration Coverage (Cmax):</strong><br/>
            Maximum task complexity represented in the demonstrations.
          </p>
          <p>
            <strong className="text-cyan-300">Extrapolation Distance (Dext):</strong><br/>
            Dext = Ctest - Cmax<br/>
            How far the test task lies beyond the demonstrated coverage.
          </p>
        </div>
        <div>
          <h3 className="font-bold text-slate-100 mb-4 uppercase text-xs tracking-widest border-b border-slate-700 pb-2">What counts as evidence?</h3>
          <ul className="space-y-4">
            <li className="flex items-center"><span className="inline-block bg-green-900/50 text-green-300 text-[10px] font-bold px-2 py-0.5 rounded uppercase mr-3 border border-green-700 w-32 text-center shadow-[0_0_10px_rgba(34,197,94,0.2)]">OUR LIVE EXPERIMENT</span><span>Results generated by this project&apos;s backend.</span></li>
            <li className="flex items-center"><span className="inline-block bg-blue-900/50 text-blue-300 text-[10px] font-bold px-2 py-0.5 rounded uppercase mr-3 border border-blue-700 w-32 text-center shadow-[0_0_10px_rgba(59,130,246,0.2)]">PUBLISHED</span><span>Claims directly supported by cited research.</span></li>
            <li className="flex items-center"><span className="inline-block bg-slate-800 text-slate-300 text-[10px] font-bold px-2 py-0.5 rounded uppercase mr-3 border border-slate-600 w-32 text-center">ILLUSTRATIVE</span><span>Visual explanation only.</span></li>
          </ul>
        </div>
      </section>

      <ExperimentPanel />

      <BdhCqModule />

      <footer className="mt-24 text-center text-sm text-slate-600 py-12 border-t border-slate-800/50">
        Coverage Cliff - Pathway / DataForge 2026 Pathway Track
      </footer>
    </main>
  );
}
