import { ExperimentPanel } from '../components/ExperimentPanel';
import { BdhCqModule } from '../components/BdhCqModule';

export default function Home() {
  return (
    <main className="min-h-screen p-8 max-w-6xl mx-auto font-sans bg-gray-50 text-gray-900">
      <header className="mb-12 text-center pt-12">
        <h1 className="text-6xl font-extrabold tracking-tight mb-4 text-black uppercase">
          Coverage Cliff
        </h1>
        <h2 className="text-2xl text-gray-700 max-w-3xl mx-auto font-medium mb-6">
          How far can a model generalize beyond what its demonstrations actually cover?
        </h2>
        <p className="text-lg text-gray-600 max-w-2xl mx-auto mb-10">
          Give a model examples of a rule. We increase the task complexity beyond those examples and measure when, if ever, its accuracy breaks.
        </p>
      </header>

      <section className="mb-16 max-w-4xl mx-auto text-center bg-white p-8 rounded-xl border-l-4 border-black shadow-sm">
        <h3 className="text-sm font-bold uppercase tracking-widest text-gray-500 mb-4">Falsifiable Claim</h3>
        <p className="text-2xl italic font-serif text-gray-900">
          "A model can appear to generalize successfully within the complexity of its demonstrations, yet fail sharply when the same underlying rule is pushed beyond that demonstrated coverage."
        </p>
        <div className="mt-6 bg-yellow-50 text-yellow-900 p-4 rounded text-sm text-left border border-yellow-200">
          <strong>IMPORTANT:</strong> This is a task- and model-specific hypothesis, not a universal law of AI.
        </div>
      </section>

      <section className="max-w-4xl mx-auto grid grid-cols-1 md:grid-cols-2 gap-8 text-sm text-gray-700 mb-16 bg-white p-8 rounded-xl border shadow-sm">
        <div>
          <h3 className="font-bold text-gray-900 mb-4 uppercase text-xs tracking-widest border-b pb-2">Terminology</h3>
          <p className="mb-4">
            <strong className="text-black">Demonstration Coverage (Cmax):</strong><br/>
            Maximum task complexity represented in the demonstrations.
          </p>
          <p>
            <strong className="text-black">Extrapolation Distance (Dext):</strong><br/>
            Dext = Ctest - Cmax<br/>
            How far the test task lies beyond the demonstrated coverage.
          </p>
        </div>
        <div>
          <h3 className="font-bold text-gray-900 mb-4 uppercase text-xs tracking-widest border-b pb-2">What counts as evidence?</h3>
          <ul className="space-y-3">
            <li><span className="inline-block bg-green-100 text-green-800 text-[10px] font-bold px-2 py-0.5 rounded uppercase mr-2 border border-green-200">OUR LIVE EXPERIMENT</span>Results generated by this project's backend.</li>
            <li><span className="inline-block bg-blue-100 text-blue-800 text-[10px] font-bold px-2 py-0.5 rounded uppercase mr-2 border border-blue-200">PUBLISHED</span>Claims directly supported by cited research.</li>
            <li><span className="inline-block bg-gray-100 text-gray-800 text-[10px] font-bold px-2 py-0.5 rounded uppercase mr-2 border border-gray-200">ILLUSTRATIVE</span>Visual explanation only.</li>
          </ul>
        </div>
      </section>

      <ExperimentPanel />

      <BdhCqModule />

      <footer className="mt-24 text-center text-sm text-gray-400 py-12 border-t">
        Coverage Cliff - Pathway / DataForge 2026 Pathway Track
      </footer>
    </main>
  );
}
